"""
schemas.py — Pydantic Structured Output Models
================================================
Module 3: Structured Data Extraction via LLM + Pydantic

These models define the contract for what the LLM must extract from
free-form guard reports. The `instructor` library enforces this schema
at call time and retries automatically on validation failure.
"""

from pydantic import BaseModel, Field
from typing import Optional, Literal


class IncidentReport(BaseModel):
    """
    Structured incident report extracted from a guard's natural-language input.
    Used as the output schema for the extraction node in the LangGraph pipeline.
    """

    location: str = Field(
        description=(
            "Exact physical location where the incident occurred. "
            "E.g., 'Gate No. 2', 'Block B Parking Level 1', 'Main Lobby Reception'. "
            "Be specific — use what is mentioned in the report."
        )
    )
    object_involved: str = Field(
        description=(
            "Primary object, person, or hazard involved. "
            "E.g., 'Unattended black backpack', 'Unknown male in grey hoodie', "
            "'Smoke from server room', 'Unconscious employee'."
        )
    )
    threat_level: Literal["Low", "Medium", "High"] = Field(
        description=(
            "Classified threat level: "
            "HIGH — immediate danger (bomb/explosive, active fire, armed intruder, "
            "medical emergency, active shooter, bomb threat); "
            "MEDIUM — situation requiring prompt attention (suspicious person loitering, "
            "unauthorized access attempt, minor altercation, abandoned vehicle); "
            "LOW — routine/administrative (lost property, noise complaint, "
            "visitor overstay, minor policy breach)."
        )
    )
    summary: str = Field(
        description=(
            "Clear 1–2 sentence summary of what happened, in English or Marathi. "
            "Include the most critical facts: who/what, where, when (if known)."
        )
    )
    reported_by: Optional[str] = Field(
        default="Unknown Guard",
        description="Name or ID of the guard submitting the report, if mentioned."
    )
    incident_time: Optional[str] = Field(
        default=None,
        description="Time or date of incident if explicitly mentioned, e.g., '14:35', 'around 3 PM'."
    )
    action_taken: Optional[str] = Field(
        default="No action taken yet",
        description="Any immediate action already taken by the guard before submitting this report."
        confidence_score: float = Field(
        description="LLM cha threat level classification varil aatpmajavishwas (0.0 te 1.0 chya darmiyan)",
        ge=0.0,
        le=1.0
    )


class AgentResponse(BaseModel):
    """
    Final response generated by the agent combining structured report
    data with SOP-matched action guidance.
    """

    incident_report: IncidentReport = Field(
        description="The structured incident report extracted from guard input."
    )
    sop_action: Optional[str] = Field(
        default=None,
        description=(
            "Relevant SOP action steps retrieved from the AP Securitas knowledge base. "
            "Only populated when threat_level is HIGH."
        )
    )
    alert_message: str = Field(
        description=(
            "Clear, direct, actionable 2–3 sentence instruction for the guard on the ground. "
            "Use simple language. Start with the most urgent action."
        )
    )
    requires_immediate_action: bool = Field(
        description="True if threat_level is HIGH and immediate escalation is required."
    )
    protocol_number: Optional[str] = Field(
        default=None,
        description="Matched SOP protocol number, e.g., 'Protocol 101'. Null if no match."
    )
